name: cache dependencies
description: Cache node_modules directory to speed up workflows
inputs:
  caching:
    description: 'Enable or disable caching'
    required: false
    default: 'true'
outputs:
  cache-info:
    description: 'Indicates if caching was enabled or disabled' 
    value: ${{ steps.cache-info-output.outputs.cache }}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching == 'true' }}
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
      run: npm ci
      shell: bash
    - name: Caching Info Output
      id: cache-info-output
      run: |
        echo 'Cache Info Outputing Step'
        echo "cache=${{ inputs.caching }}" >> $GITHUB_OUTPUT
      shell: bash

